server:
  port: 8083
  servlet:
    session:
      cookie:
        name: sessionid_mobile
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/runscore?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: rescore666
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: localhost
    password: rescore666
  session:
    store-type: redis
    timeout: 7200s
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
redisson:
  password: rescore666
  singleServerConfig:
    address: 127.0.0.1:6379
jetcache:
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      uri: redis://rescore666@127.0.0.1:6379/